/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "formapi",
            "endpoint": "https://ttvmjvxqy6.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:f4db7668-3f00-4aec-8a75-6b97000c0baf",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_CFAxNcr7P",
    "aws_user_pools_web_client_id": "4j4pcr1brpi92nuq61q3a2oc1r",
    "oauth": {}
};


export default awsmobile;
