/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "formapi",
            "endpoint": "https://ttvmjvxqy6.execute-api.us-east-1.amazonaws.com/staging",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:4a6e5025-d4b7-4e35-bb02-e3dca0ec1e54",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_6Zxy4SrFv",
    "aws_user_pools_web_client_id": "7ddfpdir0i6gmmt3en8nvf1q5r",
    "oauth": {}
};


export default awsmobile;
