/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "formapi",
            "endpoint": "https://98rxkggn7e.execute-api.us-east-1.amazonaws.com/prod",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:b4f46077-db35-4b66-af6d-b2b6e769e1e1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4xGVGCtQI",
    "aws_user_pools_web_client_id": "17gl7c5nl2umjkg19cuqpd3ig7",
    "oauth": {}
};


export default awsmobile;
